repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        stages: [commit]
        types: [python]
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        name: black (python)
        stages: [commit]
        types: [python]
